#! /usr/bin/env bash

HASKELL_DIR=/usr/local/bin

create_executables() {
    for var in "$@"
    do
        (create_simple_executable $var)
    done
}

create_simple_executable() {
# this is inspired by part of asdf-haskell: https://github.com/vic/asdf-haskell
    echo "creating $HASKELL_DIR/$1..."
    echo "#!/usr/bin/env bash" | sudo tee --append $HASKELL_DIR/$1 > /dev/null
    echo "exec $HASKELL_DIR/stack exec $1 -- \$*" | sudo tee --append $HASKELL_DIR/$1  > /dev/null
    sudo chmod +x $HASKELL_DIR/$1
}

remove_haskell_links() {
    for var in "$@"
    do
        (remove_single_file $var)
    done
}

remove_single_file() {
    echo "removing $HASKELL_DIR/$1..."
    sudo rm $HASKELL_DIR/$1
}

if [ "$1" = "uninstall" ] ; then
    remove_haskell_links ghc ghci ghc-pkg haddock runghc runhaskell
else
    create_executables ghc ghci ghc-pkg haddock runghc runhaskell
fi
