#! /usr/bin/env bash

HASKELL_DIR=/usr/local/bin

print_help() {
    echo "haskell_setup - installing haskell toolset using 'stack'*"
    echo ""
    echo "Usage: "
    echo "  haskell_setup <install|uninstall>"
    echo ""
    echo "Examples:"
    echo "haskell_setup install"
    echo "  installs stack & haskell toolset*"
    echo "haskell_setup uninstall - removes stack & haskell toolset*"
    echo ""
    echo "haskell_toolset: ghc ghci ghc-pkg haddock runghc runhaskell "
}

create_executables() {
    for var in "$@"
    do
        (create_simple_executable $var)
    done
}

create_simple_executable() {
# this is inspired by part of asdf-haskell: https://github.com/vic/asdf-haskell
    echo "creating $HASKELL_DIR/$1..."
    echo "#!/usr/bin/env bash" | sudo tee --append $HASKELL_DIR/$1 > /dev/null
    echo "exec $HASKELL_DIR/stack exec $1 -- \$*" | sudo tee --append $HASKELL_DIR/$1  > /dev/null
    sudo chmod +x $HASKELL_DIR/$1
}

remove_haskell_links() {
    for var in "$@"
    do
        (remove_single_file $var)
    done
}

remove_single_file() {
    echo "removing $HASKELL_DIR/$1..."
    sudo rm $HASKELL_DIR/$1
}

case "$1" in 
    "install"  )  create_executables ghc ghci ghc-pkg haddock runghc runhaskell  ;;
    "uninstall" ) remove_haskell_links ghc ghci ghc-pkg haddock runghc runhaskell ;;
    * ) print_help ;;
esac

